package com.taochejian.execute;

import io.appium.java_client.android.AndroidDriver;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.openqa.selenium.By;
import com.taochejian.element.TaochejianElement;
import com.taochejian.util.Assertion;
import com.taochejian.util.Operation;
import com.taochejian.util.util;

public class CheckCarCase {

	public static Logger log = LoggerFactory.getLogger(CheckCarCase.class);
	
	
	public static void checkCar(AndroidDriver driver){
		
		log.info("开始检测车辆");
		util.setInputAppiumMethod();
		driver.findElement(By.id(TaochejianElement.WEIJIAN)).click();
		driver.findElement(By.xpath(TaochejianElement.YYCZC)).click();
		util.sleep(1);	
		util.sleep(3);
		util.swipe(driver, By.xpath(TaochejianElement.TYPE_INPUT), 1);
//		util.scrollTo(driver, By.xpath(TaochejianElement.TYPE_INPUT), "手动输入车辆品牌型号的非汉字部分");
		util.sleep(2);
		if(util.isElementExist(driver, By.xpath(TaochejianElement.TYPE_INPUT)) == true){
			log.info("元素已找到，请继续");
			driver.findElement(By.xpath(TaochejianElement.TYPE_INPUT)).sendKeys("RS77806DYI");
		}else {
			log.info("元素不可见！");
			Assertion.assertEquals(false, true, "元素不可见！");
		}
		util.sleep(2);
		driver.findElement(By.xpath(TaochejianElement.FDJ_NUM)).sendKeys("6092876578");
		util.sleep(1);
		driver.findElement(By.xpath(TaochejianElement.CDRQ_BTN)).click();
		driver.findElement(By.id(TaochejianElement.CDRQ_TRUE)).click();
		log.info("选则载客人数");
		driver.findElement(By.xpath(TaochejianElement.ZKRS)).click();
		driver.findElement(By.id(TaochejianElement.ZKRS_TRUE)).click();
		util.sleep(2);
		Operation.swipeToUp(driver, 150, 1);
		util.sleep(1);
		log.info("年检到期");
		driver.findElement(By.xpath(TaochejianElement.NJDQ)).click();
		driver.findElement(By.id(TaochejianElement.NJDQ_TRUE)).click();
		util.sleep(1);
		driver.findElement(By.id(TaochejianElement.NEXT_BTN)).click();
		util.sleep(10);
		log.info("手续信息-登记证页");
		driver.findElement(By.id(TaochejianElement.NOSEE)).click();
		driver.tap(1, 1750, 730, 1);
		util.sleep(1);
		driver.findElement(By.id(TaochejianElement.COLLOR_TRUE)).click();
		log.info("选则国产or进口");
		driver.tap(1, 1780, 990, 1);
		util.swipe(driver, By.xpath(TaochejianElement.NO_POWER), 1);
		util.sleep(3);
//		driver.findElement(By.xpath(TaochejianElement.NO_POWER)).click();
		driver.tap(1, 1750, 290, 1);
		util.sleep(1);
		log.info("出厂日期");
		driver.tap(1, 1750, 450, 1);
		driver.findElement(By.id(TaochejianElement.DATE_TRUE)).click();
		log.info("过户次数");
		driver.tap(1, 1750, 600, 1);
		driver.findElement(By.id(TaochejianElement.GUOHU_TIMES)).click();
		util.sleep(1);
//		driver.findElement(By.xpath(TaochejianElement.NOW_USER)).click();
		log.info("现使用方");
		driver.tap(1, 1650, 850, 1);
		util.sleep(1);
//		driver.findElement(By.xpath(TaochejianElement.FORUS)).click();
		log.info("获得方式");
		driver.tap(1, 1560, 980, 1);
		util.sleep(1);
		Operation.swipeToUp(driver, 200, 1);
		driver.findElement(By.id(TaochejianElement.DJZ_NEXT)).click();
		util.sleep(5);
		log.info("下一步完成，进入其他信息页面");
		log.info("购车发票");
		util.sleep(1);
		driver.tap(1, 1550, 210, 1);
		util.sleep(1);
		log.info("购置税本");
		driver.tap(1, 1550, 350, 1);
		util.sleep(1);
		log.info("钥匙数量");
		driver.tap(1, 1550, 490, 1);
		util.sleep(1);
		log.info("环保标准");
		driver.tap(1, 1550, 635, 1);
		util.sleep(1);
		log.info("交强险日期");
		driver.tap(1, 1250, 780, 1);
		util.sleep(1);
		driver.findElement(By.xpath(TaochejianElement.KILOUMITER)).sendKeys("368740");
		util.sleep(1);
		log.info("变速箱");
		driver.tap(1, 1760, 1050, 1);
		util.sleep(1);
		Operation.swipeToUp(driver, 150, 1);
		util.sleep(2);
		log.info("驱动方式");
		driver.tap(1, 1550, 200, 1);
		util.sleep(1);
		log.info("车身结构");
		driver.tap(1, 1550, 345, 1);
		util.sleep(1);
		driver.findElement(By.id(TaochejianElement.QITA_NEXT)).click();
		util.sleep(1);
		log.info("下一步操作完成,开始配置信息操作");
		util.sleep(1);
		log.info("气囊数");
		driver.tap(1, 1750, 210, 1);
		util.sleep(1);
		log.info("ABS");
		driver.tap(1, 1750, 360, 1);
		util.sleep(1);
		log.info("转向助力");
		driver.tap(1, 1750, 500, 1);
		util.sleep(1);
		log.info("天窗");
		driver.tap(1, 1750, 640, 1);
		util.sleep(1);
		log.info("电动车窗");
		driver.tap(1, 1750, 780, 1);
		util.sleep(1);
		log.info("座椅材质");
		driver.tap(1, 1750, 910, 1);
		util.sleep(1);
		log.info("座椅功能");
		driver.tap(1, 1750, 1050, 1);
		util.sleep(1);
		util.swipe(driver, By.xpath(TaochejianElement.ZISHIYING), 1);
		util.sleep(1);
		driver.findElement(By.xpath(TaochejianElement.ZISHIYING)).click();
		util.sleep(1);
		log.info("后视镜");
		driver.findElement(By.xpath(TaochejianElement.HOUSHIJING)).click();
		util.sleep(1);
		log.info("空调");
		driver.findElement(By.xpath(TaochejianElement.KONGTIAO)).click();
		util.sleep(1);
		log.info("影音娱乐");
		driver.findElement(By.xpath(TaochejianElement.YYYL)).click();
		util.sleep(1);
		log.info("导航");
		driver.tap(1, 1750, 910, 1);
		util.sleep(1);
		log.info("雷达");
		driver.findElement(By.xpath(TaochejianElement.LEIDA)).click();
		util.sleep(1);
		Operation.swipeToUp(driver, 200, 1);
		util.sleep(2);
		log.info("倒车影像");
		driver.tap(1, 1750, 200, 1);
		util.sleep(1);
		log.info("轮毂材质");
		driver.findElement(By.xpath(TaochejianElement.LGCZ)).click();
		util.sleep(1);
		log.info("智能钥匙");
		driver.tap(1, 1750, 480, 1);
		util.sleep(1);
		log.info("胎压监测");
		driver.tap(1, 1750, 610, 1);
		util.sleep(1);
		log.info("随车工具");
		driver.findElement(By.xpath(TaochejianElement.SCGJ)).click();
		util.sleep(1);
		driver.findElement(By.xpath(TaochejianElement.PEIZHI_NEXT)).click();
		util.sleep(5);
	}
}
